import PDFDocument from 'pdfkit';

export const generateJournalPDF = (journal, user) => {
  const doc = new PDFDocument({ margin: 50 });

  // --- Colors ---
  const primaryColor = '#0ea5e9'; // Ocean Blue
  const secondaryColor = '#64748b'; // Slate Gray
  const accentColor = '#f0f9ff'; // Light Blue Background

  // --- Header Section ---
  // Logo placeholder (circle)
  doc.circle(50, 50, 20).fill(primaryColor);
  doc.fillColor('white').fontSize(20).text('NC', 36, 42);
  
  // Title
  doc.fillColor('#1e293b').fontSize(24).font('Helvetica-Bold')
     .text('NeuroCompanion Report', 80, 40);
  
  doc.fontSize(10).font('Helvetica').fillColor(secondaryColor)
     .text('Mental Health & Wellness Journal', 80, 70);

  // Divider
  doc.moveDown(2);
  doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(50, 90).lineTo(550, 90).stroke();
  doc.moveDown(2);

  // --- Patient Info Section ---
  doc.rect(50, 110, 500, 70).fill(accentColor);
  
  doc.fillColor('#1e293b').fontSize(12).font('Helvetica-Bold').text('Patient Information', 70, 125);
  
  doc.font('Helvetica').fontSize(10).fillColor(secondaryColor);
  doc.text(`Name: ${user.name}`, 70, 145);
  doc.text(`Email: ${user.email}`, 70, 160);
  
  doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 350, 145);
  doc.text(`Journal Date: ${new Date(journal.createdAt).toLocaleDateString()}`, 350, 160);

  doc.moveDown(4);

  // --- Analysis Dashboard (Grid Layout) ---
  const startY = 210;
  
  // Helper to draw stat card
  const drawStatCard = (x, label, value, color) => {
    doc.roundedRect(x, startY, 150, 60, 5).fill('white').stroke('#e2e8f0');
    doc.fillColor(secondaryColor).fontSize(10).text(label, x + 15, startY + 15);
    doc.fillColor(color).fontSize(16).font('Helvetica-Bold').text(value, x + 15, startY + 35);
  };

  // Mood Card
  let moodColor = '#22c55e'; // Green
  if (['sad', 'anxious', 'angry'].includes(journal.mood?.toLowerCase())) moodColor = '#ef4444'; // Red
  drawStatCard(50, 'Detected Mood', journal.mood || 'Neutral', moodColor);

  // Sentiment Card
  let sentimentColor = '#3b82f6'; // Blue
  if (journal.sentiment === 'negative') sentimentColor = '#ef4444';
  drawStatCard(225, 'Sentiment', journal.sentiment || 'Neutral', sentimentColor);

  // Stress Card
  let stressColor = '#22c55e';
  if (journal.stressLevel === 'high') stressColor = '#ef4444';
  else if (journal.stressLevel === 'medium') stressColor = '#eab308'; // Yellow
  drawStatCard(400, 'Stress Level', journal.stressLevel || 'Low', stressColor);

  doc.moveDown(6);

  // --- Summary Section ---
  if (journal.summary) {
    doc.fillColor('#1e293b').fontSize(14).font('Helvetica-Bold').text('Executive Summary', 50, 300);
    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(11).fillColor('#334155').lineGap(4)
       .text(journal.summary, { width: 500, align: 'justify' });
    doc.moveDown(2);
  }

  // --- Full Transcript Section ---
  const contentY = doc.y;
  doc.fillColor('#1e293b').fontSize(14).font('Helvetica-Bold').text('Full Transcript / Content', 50, contentY);
  doc.moveDown(0.5);
  
  // Light gray background for transcript
  doc.rect(50, doc.y, 500, 10).fill('#f8fafc'); // Placeholder for background start
  
  doc.font('Courier').fontSize(10).fillColor('#475569').lineGap(3)
     .text(journal.content, { width: 500, align: 'left' });

  // --- Footer ---
  const pageHeight = doc.page.height;
  doc.fontSize(8).fillColor('#94a3b8').text(
    'Generated by NeuroCompanion - AI-Powered Mental Health Assistant',
    50,
    pageHeight - 50,
    { align: 'center' }
  );

  return doc;
};

export const generateWeeklyReportPDF = (caregiver, patient, data) => {
  const doc = new PDFDocument({ margin: 50 });

  // --- Colors ---
  const primaryColor = '#7c3aed'; // Lavender/Purple for Weekly Report
  const secondaryColor = '#64748b';
  const accentColor = '#f5f3ff'; // Light Purple Background

  // --- Header ---
  doc.circle(50, 50, 20).fill(primaryColor);
  doc.fillColor('white').fontSize(20).text('NC', 36, 42);
  
  doc.fillColor('#1e293b').fontSize(24).font('Helvetica-Bold')
     .text('Weekly Wellness Summary', 80, 40);
  
  doc.fontSize(10).font('Helvetica').fillColor(secondaryColor)
     .text(`Report for ${data.startDate} - ${data.endDate}`, 80, 70);

  doc.moveDown(2);
  doc.strokeColor('#e2e8f0').lineWidth(1).moveTo(50, 90).lineTo(550, 90).stroke();
  doc.moveDown(2);

  // --- Patient Info ---
  doc.rect(50, 110, 500, 60).fill(accentColor);
  doc.fillColor('#1e293b').fontSize(12).font('Helvetica-Bold').text('Patient Overview', 70, 125);
  doc.font('Helvetica').fontSize(10).fillColor(secondaryColor);
  doc.text(`Patient: ${patient.name}`, 70, 145);
  doc.text(`Caregiver: ${caregiver.name}`, 350, 145);

  // --- Stats Grid ---
  const startY = 190;
  const drawStatCard = (x, label, value, subtext) => {
    doc.roundedRect(x, startY, 150, 70, 5).fill('white').stroke('#e2e8f0');
    doc.fillColor(secondaryColor).fontSize(10).text(label, x + 15, startY + 15);
    doc.fillColor(primaryColor).fontSize(20).font('Helvetica-Bold').text(value, x + 15, startY + 40);
    if (subtext) {
      doc.fillColor('#94a3b8').fontSize(8).font('Helvetica').text(subtext, x + 15, startY + 55);
    }
  };

  drawStatCard(50, 'Journal Entries', data.journalCount.toString(), 'This week');
  drawStatCard(225, 'Tasks Completed', `${data.taskCompletionRate}%`, `${data.completedTasks}/${data.totalTasks} tasks`);
  drawStatCard(400, 'Avg Stress Level', data.avgStress || 'N/A', 'Based on journals');

  doc.moveDown(8);

  // --- Mood Trend ---
  doc.fillColor('#1e293b').fontSize(14).font('Helvetica-Bold').text('Mood & Emotion Summary', 50, 290);
  doc.moveDown(0.5);
  
  if (data.emotions && data.emotions.length > 0) {
    doc.font('Helvetica').fontSize(10).fillColor(secondaryColor);
    data.emotions.forEach((e, i) => {
      const date = new Date(e.createdAt).toLocaleDateString();
      doc.text(`• ${date}: ${e.emotion} (Intensity: ${e.intensity || 'N/A'})`, { indent: 10 });
    });
  } else {
    doc.font('Helvetica-Oblique').fontSize(10).fillColor('#94a3b8').text('No mood data recorded this week.');
  }

  doc.moveDown(2);

  // --- Recent Journals ---
  doc.fillColor('#1e293b').fontSize(14).font('Helvetica-Bold').text('Recent Journal Highlights', 50, doc.y);
  doc.moveDown(0.5);

  if (data.journals && data.journals.length > 0) {
    data.journals.slice(0, 3).forEach(j => {
      doc.font('Helvetica-Bold').fontSize(11).fillColor(primaryColor).text(j.title);
      doc.font('Helvetica').fontSize(10).fillColor(secondaryColor).text(j.summary || j.content.substring(0, 100) + '...');
      doc.moveDown(0.5);
    });
  } else {
    doc.font('Helvetica-Oblique').fontSize(10).fillColor('#94a3b8').text('No journal entries this week.');
  }

  // --- Footer ---
  const pageHeight = doc.page.height;
  doc.fontSize(8).fillColor('#94a3b8').text(
    'Confidential Weekly Report - NeuroCompanion',
    50,
    pageHeight - 50,
    { align: 'center' }
  );

  return doc;
};
